# Generated by Django 5.2.6 on 2025-09-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(choices=[('A', 'Turno A (07:00-19:00)'), ('B', 'Turno B (19:00-07:00)')], max_length=1, unique=True, verbose_name='Nome'),
        ),
    ]
