# Generated by Django 5.2.6

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0006_add_display_order_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Template')),
                ('template_type', models.CharField(choices=[('SPOT', 'Análises Pontuais'), ('COMPOSITE', 'Amostras Compostas'), ('BOTH', 'Ambos')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('excel_file', models.FileField(help_text='Arquivo Excel de exemplo', upload_to='import_templates/', verbose_name='Arquivo Excel')),
                ('instructions', models.TextField(blank=True, help_text='Instruções para preenchimento', verbose_name='Instruções')),
                ('required_columns', models.JSONField(default=list, help_text='Lista de colunas obrigatórias', verbose_name='Colunas Obrigatórias')),
                ('optional_columns', models.JSONField(default=list, help_text='Lista de colunas opcionais', verbose_name='Colunas Opcionais')),
                ('field_mapping', models.JSONField(default=dict, help_text='Mapeamento entre colunas Excel e campos do sistema', verbose_name='Mapeamento de Campos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Template de Importação',
                'verbose_name_plural': 'Templates de Importação',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='imports/', verbose_name='Arquivo Excel')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Total de Linhas')),
                ('processed_rows', models.PositiveIntegerField(default=0, verbose_name='Linhas Processadas')),
                ('successful_rows', models.PositiveIntegerField(default=0, verbose_name='Linhas com Sucesso')),
                ('failed_rows', models.PositiveIntegerField(default=0, verbose_name='Linhas com Erro')),
                ('error_log', models.TextField(blank=True, verbose_name='Log de Erros')),
                ('success_log', models.TextField(blank=True, verbose_name='Log de Sucessos')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality_control.importtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão de Importação',
                'verbose_name_plural': 'Sessões de Importação',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='Número da Linha')),
                ('column_name', models.CharField(blank=True, max_length=100, verbose_name='Nome da Coluna')),
                ('error_type', models.CharField(max_length=50, verbose_name='Tipo de Erro')),
                ('error_message', models.TextField(verbose_name='Mensagem de Erro')),
                ('raw_data', models.TextField(blank=True, verbose_name='Dados Brutos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='quality_control.importsession')),
            ],
            options={
                'verbose_name': 'Erro de Importação',
                'verbose_name_plural': 'Erros de Importação',
                'ordering': ['row_number'],
            },
        ),
    ]
