# Generated by Django 5.2.6

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('quality_control', '0010_add_sequence_to_composite_sample'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('COMPLETED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('observations', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.shift', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Cadastro de Produção',
                'verbose_name_plural': 'Cadastros de Produção',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLineRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productionlines', to='quality_control.productionregistration', verbose_name='Produção')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.productionline', verbose_name='Linha de Produção')),
            ],
            options={
                'verbose_name': 'Linha de Produção',
                'verbose_name_plural': 'Linhas de Produção',
            },
        ),
        migrations.CreateModel(
            name='ProductionProductRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo do Produto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='quality_control.productionregistration', verbose_name='Produção')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality_control.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produto da Produção',
                'verbose_name_plural': 'Produtos da Produção',
            },
        ),
        migrations.CreateModel(
            name='SpotAnalysisRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('pontual_number', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], verbose_name='Número da Pontual')),
                ('analysis_result', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Reprovado')], default='PENDING', max_length=20, verbose_name='Resultado da Análise')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('analysis_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality_control.analysistype', verbose_name='Tipo de Análise')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality_control.product', verbose_name='Produto')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality_control.productionregistration', verbose_name='Produção')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.productionline', verbose_name='Local de Produção')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.shift', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Registro de Análise Pontual',
                'verbose_name_plural': 'Registros de Análise Pontual',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpotAnalysisPropertyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidade')),
                ('test_method', models.CharField(blank=True, max_length=100, verbose_name='Método de Teste')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_results', to='quality_control.spotanalysisregistration', verbose_name='Análise')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality_control.property', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Resultado de Propriedade',
                'verbose_name_plural': 'Resultados de Propriedades',
            },
        ),
        migrations.AddConstraint(
            model_name='productionregistration',
            constraint=models.UniqueConstraint(fields=('date', 'shift'), name='unique_production_date_shift'),
        ),
        migrations.AddConstraint(
            model_name='productionlineregistration',
            constraint=models.UniqueConstraint(fields=('production', 'production_line'), name='unique_production_line'),
        ),
        migrations.AddConstraint(
            model_name='productionproductregistration',
            constraint=models.UniqueConstraint(fields=('production', 'product'), name='unique_production_product'),
        ),
        migrations.AddConstraint(
            model_name='spotanalysispropertyresult',
            constraint=models.UniqueConstraint(fields=('analysis', 'property'), name='unique_analysis_property'),
        ),
    ]
