# Generated by Django 5.2.6 on 2025-09-26 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_shift_name'),
        ('quality_control', '0013_fix_spot_sample_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spotanalysis',
            options={'ordering': ['property__display_order'], 'verbose_name': 'Análise Pontual', 'verbose_name_plural': 'Análises Pontuais'},
        ),
        migrations.RemoveConstraint(
            model_name='spotanalysis',
            name='unique_spot_analysis_per_sample',
        ),
        migrations.RemoveConstraint(
            model_name='spotsample',
            name='unique_spot_sample',
        ),
        migrations.AlterUniqueTogether(
            name='spotanalysis',
            unique_together={('spot_sample', 'property')},
        ),
        migrations.AlterField(
            model_name='spotanalysis',
            name='spot_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_control.spotsample', verbose_name='Amostra Pontual'),
        ),
        migrations.AlterUniqueTogether(
            name='spotsample',
            unique_together={('date', 'shift', 'production_line', 'product', 'sequence')},
        ),
        migrations.RemoveField(
            model_name='spotanalysis',
            name='analysis_type',
        ),
        migrations.RemoveField(
            model_name='spotanalysis',
            name='date',
        ),
        migrations.RemoveField(
            model_name='spotanalysis',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='spotanalysis',
            name='product',
        ),
        migrations.RemoveField(
            model_name='spotanalysis',
            name='production_line',
        ),
        migrations.RemoveField(
            model_name='spotanalysis',
            name='sample_time',
        ),
        migrations.RemoveField(
            model_name='spotanalysis',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='spotanalysis',
            name='shift',
        ),
    ]
