# Generated by Django 5.2.6 on 2025-09-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0013_fix_spot_sample_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spotanalysis',
            options={'ordering': ['property__display_order'], 'verbose_name': 'Análise Pontual', 'verbose_name_plural': 'Análises Pontuais'},
        ),
        migrations.RemoveConstraint(
            model_name='spotanalysis',
            name='unique_spot_analysis_per_sample',
        ),
        migrations.RemoveConstraint(
            model_name='spotsample',
            name='unique_spot_sample',
        ),
        migrations.AlterUniqueTogether(
            name='analysistypeproperty',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='chemicalanalysisresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='compositesampleresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productpropertymap',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='spotanalysis',
            name='analysis_type',
        ),
        migrations.RemoveField(
            model_name='spotanalysis',
            name='date',
        ),
        migrations.RemoveField(
            model_name='spotanalysis',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='spotanalysis',
            name='product',
        ),
        migrations.RemoveField(
            model_name='spotanalysis',
            name='production_line',
        ),
        migrations.RemoveField(
            model_name='spotanalysis',
            name='sample_time',
        ),
        migrations.RemoveField(
            model_name='spotanalysis',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='spotanalysis',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='spotsample',
            name='sequence',
        ),
        migrations.AddField(
            model_name='spotsample',
            name='sample_sequence',
            field=models.PositiveIntegerField(default=1, verbose_name='Sequência da Amostra'),
        ),
    ]
