# Generated by Django 5.2.6 on 2025-09-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0014_alter_spotanalysis_options_and_more'),
    ]

    operations = [
    ]
