# Generated by Django 5.2.6 on 2025-09-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0015_auto_20250926_0953'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analysistypeproperty',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='chemicalanalysisresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='compositesampleresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productpropertymap',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='spotanalysis',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='spotsample',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='spotsample',
            name='sample_sequence',
            field=models.PositiveIntegerField(default=1, verbose_name='Sequência da Amostra'),
        ),
        migrations.RemoveField(
            model_name='spotsample',
            name='sequence',
        ),
    ]
